<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script type="text/javascript">
  /**
   * Promise学习 2018年4月19日15:16:37
   */
  console.dir(Promise);
  console.log(typeof Promise);//function
  console.log(typeof Promise.prototype);//object

  /**创建promise对象
   * @type {Promise<any>}
   */
  let promise = new Promise(function (resolve, reject) {
    let num = Math.random() * 10;
    setTimeout(function () {
      if (num < 5) {
        resolve(num)
      } else {
        reject(num)
      }
    }, 0)
  });
  promise.then(function (result) {
    console.log('success', result);
  }).catch(function (result) {
    console.log('fail', result);
  });


  /*
  Promise.done() / Promise. finally()
  Promise.done() 的用法类似 .then() ，可以提供resolved和rejected方法，也可以不提供任何参数，它的主要作用是在回调链的尾端捕捉前面没有被 .catch() 捕捉到的错误

  Promise. finally() 接受一个方法作为参数，这个方法不管promise最终的状态是怎样，都一定会被执行。
  */


  /**
   * .then()方法使Promise原型链上的方法，它包含两个参数方法，分别是已成功resolved的回调和已失败rejected的回调
   * .catch()的作用是捕获Promise的错误，与then()的rejected回调作用几乎一致。但是由于Promise的抛错具有冒泡性质，
   * 能够不断传递，这样就能够在下一个catch()中统一处理这些错误。同时catch()也能够捕获then()中抛出的错误，所以
   * 建议不要使用then()的rejected回调，而是统一使用catch()来处理错误
   */

  //参考文档：
  // https://www.liaoxuefeng.com/wiki/001434446689867b27157e896e74d51a89c25cc8b43bdb3000/0014345008539155e93fc16046d4bb7854943814c4f9dc2000
  //http://www.hangge.com/blog/cache/detail_1638.html (很形象的例子)
</script>
</body>
</html>